import { LanguageTranslationModule } from './language-translation.module';

/**
 * @description Função que retorna a linguagem do grid de acordo com o selecionado
 * @author Alexandre A Jacobino
 * @since 1.0.0
 */
const ptbr={
    page: "Página",
    more: "daMore",
    to: "De",
    of: "De",
    next: "Próximo",
    last: "Última",
    first: "Primeiro",
    previous: "Anterior",
    loadingOoo: "Aguarde...",
    selectAll: "Selecionar Todos",
    searchOoo: "Procurar..",
    blanks: "Em branco",
    filterOoo: "Filtro...",
    applyFilter: "Aplicar Filtro...",
    equals: "Igual",
    notEqual: "Diferente",
    lessThan: "Menor Que",
    greaterThan: "Maior Que",
    lessThanOrEqual: "Menor ou Igual",
    greaterThanOrEqual: "Maior ou Igual",
    inRange: "No range",
    contains: "Contém",
    notContains: "Não Contém",
    startsWith: "Iniciar em",
    endsWith: "Terminar Em",
    andCondition: "E",
    orCondition: "OU",
    group: "Grupo",
    columns: "Colunas",
    filters: "Filtros",
    rowGroupColumns: "Colunas do Pivô",
    rowGroupColumnsEmptyMessage: "Arraste aqui para definir grupos de linhas",
    valueColumns: "Colunas de Valor",
    pivotMode: "Modo Pivô",
    groups: "Grupos",
    values: "Valores",
    pivots: "Pivôs",
    valueColumnsEmptyMessage: "la drag cols to aggregate",
    pivotColumnsEmptyMessage: "la drag here to pivot",
    toolPanelButton: "la tool panel",
    noRowsToShow: "Não foram encontrados registros",
    pinColumn: "laPin Column",
    valueAggregation: "laValue Agg",
    autosizeThiscolumn: "laAutosize Diz",
    autosizeAllColumns: "laAutsoie em All",
    groupBy: "laGroup by",
    ungroupBy: "laUnGroup by",
    resetColumns: "laReset Those Cols",
    expandAll: "Abrir todos",
    collapseAll: "Esconder Todos",
    toolPanel: "Painel de Ferramentas",
    export: "Exportação",
    csvExport: "Exportar para CSV",
    excelExport: "Exportar para Excel (.xlsx)",
    excelXmlExport: "Exportar para Excel (.xml)",
    pivotChartAndPivotMode: "Gráfico Pivô & Modo Pivô",
    pivotChart: "laPivot Chart",
    chartRange: "laChart Range",
    columnChart: "laColumn",
    groupedColumn: "laGrouped",
    stackedColumn: "laStacked",
    normalizedColumn: "la100% Stacked",
    barChart: "laBar",
    groupedBar: "laGrouped",
    stackedBar: "laStacked",
    normalizedBar: "la100% Stacked",
    pieChart: "laPie",
    pie: "laPie",
    doughnut: "laDoughnut",
    line: "laLine",
    xyChart: "laX Y (Scatter)",
    scatter: "laScatter",
    bubble: "laBubble",
    areaChart: "laArea",
    area: "laArea",
    stackedArea: "laStacked",
    normalizedArea: "la100% Stacked",
    pinLeft: "laPin &lt;&lt;",
    pinRight: "laPin &gt;&gt;",
    noPin: "laDontPin &lt;&gt;",
    sum: "laSum",
    min: "laMin",
    max: "laMax",
    none: "laNone",
    count: "laCount",
    average: "laAverage",
    filteredRows: "Linhas Filtradas",
    selectedRows: "Linhas Selecionadas",
    totalRows: "Total de Linhas",
    totalAndFilteredRows: "Total de Lihas Filtradas",
    copy: "Copiar",
    copyWithHeaders: "Cópiar com cabeçalho",
    ctrlC: "[CTRL+C]",
    paste: "Colar",
    ctrlV: "[CTRL+V]",
    pivotChartTitle: "laPivot Chart",
    rangeChartTitle: "laRange Chart",
    settings: "laSettings",
    data: "laData",
    format: "Formato",
    categories: "laCategories",
    series: "laSeries",
    axis: "laAxis",
    color: "laColor",
    thickness: "laThickness",
    xRotation: "laX Rotation",
    yRotation: "laY Rotation",
    ticks: "laTicks",
    width: "laWidth",
    length: "laLength",
    padding: "laPadding",
    chart: "laChart",
    title: "laTitle",
    font: "laFont",
    top: "laTop",
    right: "laRight",
    bottom: "laBottom",
    left: "laLeft",
    labels: "laLabels",
    size: "laSize",
    legend: "laLegend",
    position: "laPosition",
    markerSize: "laMarker Size",
    markerStroke: "laMarker Stroke",
    markerPadding: "laMarker Padding",
    itemPaddingX: "laItem Padding X",
    itemPaddingY: "laItem Padding Y",
    strokeWidth: "laStroke Width",
    offset: "laOffset",
    tooltips: "laTooltips",
    offsets: "laOffsets",
    callout: "laCallout",
    markers: "laMarkers",
    shadow: "laShadow",
    blur: "laBlur",
    xOffset: "laX Offset",
    yOffset: "laY Offset",
    lineWidth: "laLine Width",
    normal: "laNormal",
    bold: "laBold",
    italic: "laItalic",
    boldItalic: "laBold Italic",
    fillOpacity: "laFill Opacity",
    strokeOpacity: "laLine Opacity",
    columnGroup: "laColumn",
    barGroup: "laBar",
    pieGroup: "laPie",
    lineGroup: "laLine",
    scatterGroup: "laScatter",
    areaGroup: "laArea",
    groupedColumnTooltip: "laGrouped",
    stackedColumnTooltip: "laStacked",
    normalizedColumnTooltip: "la100% Stacked",
    groupedBarTooltip: "laGrouped",
    stackedBarTooltip: "laStacked",
    normalizedBarTooltip: "la100% Stacked",
    pieTooltip: "laPie",
    doughnutTooltip: "laDoughnut",
    lineTooltip: "laLine",
    groupedAreaTooltip: "laGrouped",
    stackedAreaTooltip: "laStacked",
    normalizedAreaTooltip: "la100% Stacked",
    scatterTooltip: "laScatter",
    bubbleTooltip: "laBubble",
    noDataToChart: "laNo data available to be charted.",
    pivotChartRequiresPivotMode: "laPivot Chart requires Pivot Mode enabled."
  };

export function TraduzirGrid(Translation: LanguageTranslationModule) {
    
    switch(Translation.RetornaLinguagem())
    {
    case "pt br":
        return ptbr;
        break;
    }
}